export interface Product {
  id: string;
  name: string;
  nameEn: string;
  brand: string;
  price: number;
  originalPrice?: number;
  images: string[];
  category: 'intimo' | 'pigiami' | 'beachwear' | 'calze' | 'casual';
  subcategory?: string;
  colors: number;
  sizes: string[];
  description: string;
  descriptionEn: string;
  badge?: 'NEW' | 'SALE';
  inStock: boolean;
  material?: string[]; // Array of materials (e.g., ['Cotone', 'Pizzo', 'Satin'])
  // Pack product fields
  isPack?: boolean;
  packQuantity?: number; // Fixed quantity for pack (default: 3)
  packColors?: string[]; // Array of color codes/names included in the pack
}

export const products: Product[] = [
  // Intimo products
  {
    id: 'rbd2576937j',
    name: 'Set Reggiseno e Slip Pizzo Nero',
    nameEn: 'Black Lace Bra and Panty Set',
    brand: 'Intimissimi',
    price: 39.90,
    originalPrice: 49.90,
    images: ['/media/RBD2576937J-FI.jpg', '/media/RBD2576937J-F.jpg', '/media/RBD2576937J-BI.jpg'],
    category: 'intimo',
    subcategory: 'reggiseni',
    colors: 3,
    sizes: ['S', 'M', 'L'],
    description: 'Set elegante in pizzo nero con reggiseno push-up e slip. Perfetto per un look raffinato e sensuale.',
    descriptionEn: 'Elegant black lace set with push-up bra and panty. Perfect for a refined and sensual look.',
    badge: 'SALE',
    inStock: true,
    material: ['Pizzo'],
  },
  {
    id: 'rbd2578019',
    name: 'Reggiseno Pizzo Rosso',
    nameEn: 'Red Lace Bra',
    brand: 'Intimissimi',
    price: 29.90,
    images: ['/media/RBD2578019-FI.jpg', '/media/RBD2578019-F.jpg', '/media/RBD2578019-BI.jpg'],
    category: 'intimo',
    subcategory: 'reggiseni',
    colors: 4,
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Reggiseno in pizzo rosso con ferretto e cinghie regolabili. Massimo comfort e sostegno.',
    descriptionEn: 'Red lace bra with underwire and adjustable straps. Maximum comfort and support.',
    badge: 'NEW',
    inStock: true,
    material: ['Pizzo'],
  },
  {
    id: 'bod2577938j',
    name: 'Body Elegante Pizzo Bianco',
    nameEn: 'Elegant White Lace Bodysuit',
    brand: 'Calzedonia',
    price: 45.90,
    images: ['/media/BOD2577938J-FI.jpg', '/media/BOD2577938J-F.jpg', '/media/BOD2577938J-BI.jpg'],
    category: 'intimo',
    subcategory: 'body',
    colors: 5,
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'Body in pizzo bianco elegante e raffinato. Perfetto per occasioni speciali.',
    descriptionEn: 'Elegant and refined white lace bodysuit. Perfect for special occasions.',
    badge: 'NEW',
    inStock: true,
    material: ['Pizzo'],
  },
  {
    id: 'rsd2577938j',
    name: 'Set Reggiseno e Slip Satinato',
    nameEn: 'Satin Bra and Panty Set',
    brand: 'Tezenis',
    price: 49.90,
    images: ['/media/RSD2577938J-FI.jpg', '/media/RSD2577938J-F.jpg', '/media/RSD2577938J-BI.jpg'],
    category: 'intimo',
    subcategory: 'reggiseni',
    colors: 4,
    sizes: ['S', 'M', 'L'],
    description: 'Set in satin con reggiseno senza ferretto e slip classico. Comfort e stile.',
    descriptionEn: 'Satin set with wire-free bra and classic panty. Comfort and style.',
    inStock: true,
    material: ['Satin'],
  },
  {
    id: 'rid2581942j',
    name: 'Slip Pizzo Fantasia',
    nameEn: 'Lace Pattern Panty',
    brand: 'Calzedonia',
    price: 19.90,
    images: ['/media/RID2581942J-FI.jpg', '/media/RID2581942J-F.jpg', '/media/RID2581942J-BI.jpg'],
    category: 'intimo',
    subcategory: 'slip',
    colors: 6,
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Slip in pizzo con fantasia elegante. Taglio classico e comfort garantito.',
    descriptionEn: 'Lace panty with elegant pattern. Classic cut and guaranteed comfort.',
    inStock: true,
    material: ['Pizzo'],
  },
  {
    id: 'sbd2577938j',
    name: 'Set Lingerie Satinato Rosa',
    nameEn: 'Pink Satin Lingerie Set',
    brand: 'Golden Lady',
    price: 32.90,
    images: ['/media/SBD2577938J-FI.jpg', '/media/SBD2577938J-F.jpg', '/media/SBD2577938J-BI.jpg'],
    category: 'intimo',
    subcategory: 'lingerie',
    colors: 3,
    sizes: ['S', 'M', 'L'],
    description: 'Set lingerie in satin rosa con dettagli in pizzo. Femminile e romantico.',
    descriptionEn: 'Pink satin lingerie set with lace details. Feminine and romantic.',
    inStock: true,
    material: ['Satin', 'Pizzo'],
  },
  // Pigiami products
  {
    id: 'pcd700m949j',
    name: 'Pigiama Satinato Elegante',
    nameEn: 'Elegant Satin Pajamas',
    brand: 'Tezenis',
    price: 59.90,
    images: ['/media/PCD700M949J-FI.jpg', '/media/PCD700M949J-F.jpg', '/media/PCD700M949J-BI.jpg'],
    category: 'pigiami',
    subcategory: 'pigiami-lunghi',
    colors: 4,
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Pigiama in satin elegante con pantalone lungo e camicia. Massimo comfort per la notte.',
    descriptionEn: 'Elegant satin pajamas with long pants and shirt. Maximum comfort for the night.',
    badge: 'NEW',
    inStock: true,
    material: ['Satin'],
  },
  {
    id: 'pcn12s1467',
    name: 'Pigiama Corto Estate',
    nameEn: 'Short Summer Pajamas',
    brand: 'Tezenis',
    price: 39.90,
    images: ['/media/PCN12S1467-FI.jpg', '/media/PCN12S1467-F.jpg', '/media/PCN12S1467-BI.jpg'],
    category: 'pigiami',
    subcategory: 'pigiami-corti',
    colors: 5,
    sizes: ['S', 'M', 'L'],
    description: 'Pigiama corto perfetto per l\'estate. Taglio comodo e tessuto traspirante.',
    descriptionEn: 'Short pajamas perfect for summer. Comfortable cut and breathable fabric.',
    inStock: true,
    material: ['Cotone'],
  },
  {
    id: 'pld2576945j',
    name: 'Pigiama Leisurewear',
    nameEn: 'Leisurewear Pajamas',
    brand: 'Tezenis',
    price: 49.90,
    images: ['/media/PLD2576945J-FI.jpg', '/media/PLD2576945J-F.jpg', '/media/PLD2576945J-BI.jpg'],
    category: 'pigiami',
    subcategory: 'leisurewear',
    colors: 3,
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Pigiama leisurewear comodo e casual. Perfetto per relax a casa.',
    descriptionEn: 'Comfortable and casual leisurewear pajamas. Perfect for relaxing at home.',
    badge: 'NEW',
    inStock: true,
  },
  // Beachwear products
  {
    id: 'bid49g019',
    name: 'Costume Bikini Elegante',
    nameEn: 'Elegant Bikini',
    brand: 'Calzedonia',
    price: 35.90,
    originalPrice: 49.90,
    images: ['/media/BID49G019-FI.jpg', '/media/BID49G019-F.jpg', '/media/BID49G019-BI.jpg'],
    category: 'beachwear',
    subcategory: 'bikini',
    colors: 5,
    sizes: ['S', 'M', 'L'],
    description: 'Bikini elegante con top regolabile e slip a vita alta. Perfetto per la spiaggia.',
    descriptionEn: 'Elegant bikini with adjustable top and high-waisted bottom. Perfect for the beach.',
    badge: 'SALE',
    inStock: true,
  },
  {
    id: 'cld28b019',
    name: 'Costume Intero Elegante',
    nameEn: 'Elegant One-Piece Swimsuit',
    brand: 'Calzedonia',
    price: 49.90,
    images: ['/media/CLD28B019-FI.jpg', '/media/CLD28B019-F.jpg', '/media/CLD28B019-BI.jpg'],
    category: 'beachwear',
    subcategory: 'costumi-interi',
    colors: 4,
    sizes: ['S', 'M', 'L'],
    description: 'Costume intero elegante con scollo profondo. Elegante e femminile.',
    descriptionEn: 'Elegant one-piece swimsuit with deep neckline. Elegant and feminine.',
    inStock: true,
  },
  // Calze products
  {
    id: 'gcd0376',
    name: 'Collant in Tulle con Strass',
    nameEn: 'Tulle Tights with Rhinestones',
    brand: 'Golden Lady',
    price: 12.90,
    images: ['/media/gcd0376ncn002_collant_in_tulle_con_applicazione_strass_01.jpg'],
    category: 'calze',
    subcategory: 'collant',
    colors: 2,
    sizes: ['Unica'],
    description: 'Collant in tulle elegante con applicazioni strass. Perfetto per occasioni speciali.',
    descriptionEn: 'Elegant tulle tights with rhinestone applications. Perfect for special occasions.',
    inStock: true,
    material: ['Tulle'],
  },
  {
    id: 'gcd0383',
    name: 'Collant Effetto Pizzo',
    nameEn: 'Lace Effect Tights',
    brand: 'Golden Lady',
    price: 10.90,
    images: ['/media/gcd0383ncn002_collant_effetto_pizzo_01.jpg'],
    category: 'calze',
    subcategory: 'collant',
    colors: 3,
    sizes: ['Unica'],
    description: 'Collant con effetto pizzo elegante. Perfetto per un look raffinato.',
    descriptionEn: 'Tights with elegant lace effect. Perfect for a refined look.',
    inStock: true,
  },
  // Add more products...
  {
    id: 'rbd97d019',
    name: 'Set Reggiseno e Slip Pizzo Fantasia',
    nameEn: 'Pattern Lace Bra and Panty Set',
    brand: 'Intimissimi',
    price: 42.90,
    images: ['/media/RBD97D019-FI.jpg', '/media/RBD97D019-F.jpg', '/media/RBD97D019-BI.jpg'],
    category: 'intimo',
    subcategory: 'reggiseni',
    colors: 4,
    sizes: ['S', 'M', 'L'],
    description: 'Set in pizzo con fantasia elegante. Reggiseno push-up e slip classico.',
    descriptionEn: 'Lace set with elegant pattern. Push-up bra and classic panty.',
    inStock: true,
  },
  {
    id: 'rid2576937j',
    name: 'Slip Pizzo Classico',
    nameEn: 'Classic Lace Panty',
    brand: 'Calzedonia',
    price: 16.90,
    images: ['/media/RID2576937J-FI.jpg', '/media/RID2576937J-F.jpg'],
    category: 'intimo',
    subcategory: 'slip',
    colors: 5,
    sizes: ['S', 'M', 'L'],
    description: 'Slip in pizzo classico. Taglio comodo e tessuto morbido.',
    descriptionEn: 'Classic lace panty. Comfortable cut and soft fabric.',
    inStock: true,
  },
  {
    id: 'sbd2576937j',
    name: 'Slip Pizzo Fantasia',
    nameEn: 'Pattern Lace Panty',
    brand: 'Golden Lady',
    price: 15.90,
    images: ['/media/SBD2576937J-FI.jpg', '/media/SBD2576937J-F.jpg'],
    category: 'intimo',
    subcategory: 'slip',
    colors: 4,
    sizes: ['S', 'M', 'L'],
    description: 'Slip in pizzo con fantasia elegante. Perfetto per tutti i giorni.',
    descriptionEn: 'Lace panty with elegant pattern. Perfect for everyday wear.',
    inStock: true,
  },
  // More products for variety
  {
    id: 'rbd97d028k',
    name: 'Set Reggiseno e Slip Pizzo Fantasia',
    nameEn: 'Pattern Lace Bra and Panty Set',
    brand: 'Intimissimi',
    price: 42.90,
    images: ['/media/RBD97D019-FI.jpg', '/media/RBD97D019-F.jpg', '/media/RBD97D019-BI.jpg'],
    category: 'intimo',
    subcategory: 'reggiseni',
    colors: 4,
    sizes: ['S', 'M', 'L'],
    description: 'Set in pizzo con fantasia elegante. Reggiseno push-up e slip classico.',
    descriptionEn: 'Lace set with elegant pattern. Push-up bra and classic panty.',
    inStock: true,
  },
  {
    id: 'ri1294r502i',
    name: 'Reggiseno Push-up Elegante',
    nameEn: 'Elegant Push-up Bra',
    brand: 'Intimissimi',
    price: 34.90,
    images: ['/media/RI1294R502I-FI.jpg', '/media/RI1294R502I-F.jpg', '/media/RI1294R502I-BI.jpg'],
    category: 'intimo',
    subcategory: 'reggiseni',
    colors: 3,
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Reggiseno push-up con ferretto e cinghie regolabili. Massimo sostegno.',
    descriptionEn: 'Push-up bra with underwire and adjustable straps. Maximum support.',
    badge: 'NEW',
    inStock: true,
  },
  {
    id: 'rp2577m938j',
    name: 'Slip Pizzo Classico',
    nameEn: 'Classic Lace Panty',
    brand: 'Calzedonia',
    price: 16.90,
    images: ['/media/RP2577M938J-FI.jpg', '/media/RP2577M938J-F.jpg'],
    category: 'intimo',
    subcategory: 'slip',
    colors: 5,
    sizes: ['S', 'M', 'L'],
    description: 'Slip in pizzo classico. Taglio comodo e tessuto morbido.',
    descriptionEn: 'Classic lace panty. Comfortable cut and soft fabric.',
    inStock: true,
  },
  {
    id: 'rsd65m019',
    name: 'Slip Pizzo Fantasia',
    nameEn: 'Pattern Lace Panty',
    brand: 'Golden Lady',
    price: 15.90,
    images: ['/media/RSD65M019-FI.jpg', '/media/RSD65M019-F.jpg'],
    category: 'intimo',
    subcategory: 'slip',
    colors: 4,
    sizes: ['S', 'M', 'L'],
    description: 'Slip in pizzo con fantasia elegante. Perfetto per tutti i giorni.',
    descriptionEn: 'Lace panty with elegant pattern. Perfect for everyday wear.',
    inStock: true,
  },
  {
    id: 'll2578t019',
    name: 'Body Pizzo Elegante',
    nameEn: 'Elegant Lace Bodysuit',
    brand: 'Tezenis',
    price: 38.90,
    images: ['/media/LL2578T019-FI.jpg', '/media/LL2578T019-F.jpg', '/media/LL2578T019-BI.jpg'],
    category: 'intimo',
    subcategory: 'body',
    colors: 4,
    sizes: ['S', 'M', 'L'],
    description: 'Body in pizzo elegante. Perfetto per un look raffinato.',
    descriptionEn: 'Elegant lace bodysuit. Perfect for a refined look.',
    inStock: true,
  },
  // Reggiseni - Brassiere
  {
    id: 'brassiere-001',
    name: 'Brassiere Pizzo Elegante',
    nameEn: 'Elegant Lace Brassiere',
    brand: 'Intimissimi',
    price: 34.90,
    images: ['/media/RBD2576937J-FI.jpg'],
    category: 'intimo',
    subcategory: 'brassiere',
    colors: 4,
    sizes: ['II', 'III', 'IV', 'V'],
    description: 'Brassiere in pizzo elegante con chiusura sul retro. Massimo comfort.',
    descriptionEn: 'Elegant lace brassiere with back closure. Maximum comfort.',
    inStock: true,
  },
  {
    id: 'brassiere-002',
    name: 'Brassiere Imbottitura Removibile',
    nameEn: 'Removable Padding Brassiere',
    brand: 'Intimissimi',
    price: 29.95,
    images: ['/media/RBD2578019-FI.jpg'],
    category: 'intimo',
    subcategory: 'brassiere',
    colors: 3,
    sizes: ['II', 'III', 'IV'],
    description: 'Brassiere con imbottitura removibile. Spalline regolabili.',
    descriptionEn: 'Brassiere with removable padding. Adjustable straps.',
    badge: 'NEW',
    inStock: true,
  },
  // Reggiseni - Balconcino
  {
    id: 'balconcino-001',
    name: 'Reggiseno Balconcino Pizzo',
    nameEn: 'Balcony Lace Bra',
    brand: 'Calzedonia',
    price: 32.90,
    images: ['/media/RBD2576937J-FI.jpg'],
    category: 'intimo',
    subcategory: 'balconcino',
    colors: 5,
    sizes: ['II', 'III', 'IV', 'V'],
    description: 'Reggiseno balconcino in pizzo. Taglio che valorizza il décolleté.',
    descriptionEn: 'Balcony bra in lace. Cut that enhances the décolleté.',
    inStock: true,
  },
  // Reggiseni - Triangolo
  {
    id: 'triangolo-001',
    name: 'Reggiseno Triangolo Senza Ferretto',
    nameEn: 'Wireless Triangle Bra',
    brand: 'Tezenis',
    price: 24.90,
    images: ['/media/RBD2578019-FI.jpg'],
    category: 'intimo',
    subcategory: 'triangolo',
    colors: 6,
    sizes: ['II', 'III', 'IV'],
    description: 'Reggiseno triangolo senza ferretto. Massimo comfort.',
    descriptionEn: 'Wireless triangle bra. Maximum comfort.',
    inStock: true,
  },
  // Reggiseni - Push-up
  {
    id: 'pushup-001',
    name: 'Reggiseno Push-up Imbottito',
    nameEn: 'Padded Push-up Bra',
    brand: 'Intimissimi',
    price: 36.90,
    images: ['/media/RBD2576937J-FI.jpg'],
    category: 'intimo',
    subcategory: 'pushup',
    colors: 4,
    sizes: ['II', 'III', 'IV', 'V'],
    description: 'Reggiseno push-up con ferretto e imbottitura. Effetto push-up immediato.',
    descriptionEn: 'Push-up bra with underwire and padding. Immediate push-up effect.',
    inStock: true,
  },
  {
    id: 'pushup-002',
    name: 'Reggiseno Push-up Pizzo',
    nameEn: 'Lace Push-up Bra',
    brand: 'Calzedonia',
    price: 39.90,
    images: ['/media/RBD2578019-FI.jpg'],
    category: 'intimo',
    subcategory: 'pushup',
    colors: 3,
    sizes: ['II', 'III', 'IV'],
    description: 'Reggiseno push-up in pizzo elegante. Perfetto per ogni occasione.',
    descriptionEn: 'Elegant lace push-up bra. Perfect for every occasion.',
    badge: 'SALE',
    inStock: true,
  },
  // Reggiseni - Fascia / Senza spalline
  {
    id: 'fascia-001',
    name: 'Reggiseno Fascia Senza Spalline',
    nameEn: 'Strapless Bandeau Bra',
    brand: 'Intimissimi',
    price: 31.90,
    images: ['/media/RBD2576937J-FI.jpg'],
    category: 'intimo',
    subcategory: 'fascia',
    colors: 5,
    sizes: ['II', 'III', 'IV'],
    description: 'Reggiseno fascia senza spalline. Perfetto per abiti scollati.',
    descriptionEn: 'Strapless bandeau bra. Perfect for low-cut dresses.',
    inStock: true,
  },
  // Reggiseni - Senza ferretto
  {
    id: 'senza-ferretto-001',
    name: 'Reggiseno Senza Ferretto Pizzo',
    nameEn: 'Wireless Lace Bra',
    brand: 'Tezenis',
    price: 26.90,
    images: ['/media/RBD2578019-FI.jpg'],
    category: 'intimo',
    subcategory: 'senza-ferretto',
    colors: 6,
    sizes: ['II', 'III', 'IV'],
    description: 'Reggiseno senza ferretto in pizzo. Comfort e naturalezza.',
    descriptionEn: 'Wireless lace bra. Comfort and natural feel.',
    inStock: true,
  },
  // Reggiseni - Con ferretto
  {
    id: 'con-ferretto-001',
    name: 'Reggiseno Con Ferretto Pizzo',
    nameEn: 'Underwire Lace Bra',
    brand: 'Calzedonia',
    price: 38.90,
    images: ['/media/RBD2576937J-FI.jpg'],
    category: 'intimo',
    subcategory: 'con-ferretto',
    colors: 4,
    sizes: ['II', 'III', 'IV', 'V'],
    description: 'Reggiseno con ferretto in pizzo. Massimo sostegno.',
    descriptionEn: 'Underwire lace bra. Maximum support.',
    inStock: true,
  },
  // Reggiseni - Imbottito
  {
    id: 'imbottito-001',
    name: 'Reggiseno Imbottito Pizzo',
    nameEn: 'Padded Lace Bra',
    brand: 'Intimissimi',
    price: 35.90,
    images: ['/media/RBD2578019-FI.jpg'],
    category: 'intimo',
    subcategory: 'imbottito',
    colors: 5,
    sizes: ['II', 'III', 'IV'],
    description: 'Reggiseno imbottito in pizzo. Perfetto per ogni giorno.',
    descriptionEn: 'Padded lace bra. Perfect for everyday.',
    inStock: true,
  },
  // Reggiseni - Non imbottito
  {
    id: 'non-imbottito-001',
    name: 'Reggiseno Non Imbottito Pizzo',
    nameEn: 'Unpadded Lace Bra',
    brand: 'Tezenis',
    price: 28.90,
    images: ['/media/RBD2576937J-FI.jpg'],
    category: 'intimo',
    subcategory: 'non-imbottito',
    colors: 4,
    sizes: ['II', 'III', 'IV'],
    description: 'Reggiseno non imbottito in pizzo. Look naturale e raffinato.',
    descriptionEn: 'Unpadded lace bra. Natural and refined look.',
    inStock: true,
  },
  // Slip - Slip classico
  {
    id: 'slip-classico-001',
    name: 'Slip Classico Pizzo',
    nameEn: 'Classic Lace Panty',
    brand: 'Calzedonia',
    price: 16.90,
    images: ['/media/RID2576937J-FI.jpg'],
    category: 'intimo',
    subcategory: 'slip-classico',
    colors: 6,
    sizes: ['S', 'M', 'L'],
    description: 'Slip classico in pizzo. Taglio comodo e tessuto morbido.',
    descriptionEn: 'Classic lace panty. Comfortable cut and soft fabric.',
    inStock: true,
  },
  // Slip - Fianco basso
  {
    id: 'fianco-basso-001',
    name: 'Slip Fianco Basso Pizzo',
    nameEn: 'Low Rise Lace Panty',
    brand: 'Intimissimi',
    price: 17.90,
    images: ['/media/RID2581942J-FI.jpg'],
    category: 'intimo',
    subcategory: 'fianco-basso',
    colors: 5,
    sizes: ['S', 'M', 'L'],
    description: 'Slip a fianco basso in pizzo. Moderno e comodo.',
    descriptionEn: 'Low rise lace panty. Modern and comfortable.',
    inStock: true,
  },
  // Slip - Fianco alto
  {
    id: 'fianco-alto-001',
    name: 'Slip Fianco Alto Pizzo',
    nameEn: 'High Rise Lace Panty',
    brand: 'Tezenis',
    price: 18.90,
    images: ['/media/RSD2577938J-FI.jpg'],
    category: 'intimo',
    subcategory: 'fianco-alto',
    colors: 4,
    sizes: ['S', 'M', 'L'],
    description: 'Slip a fianco alto in pizzo. Massimo comfort e sostegno.',
    descriptionEn: 'High rise lace panty. Maximum comfort and support.',
    inStock: true,
  },
  // Slip - Brasiliana
  {
    id: 'brasiliana-001',
    name: 'Slip Brasiliana Pizzo',
    nameEn: 'Brazilian Lace Panty',
    brand: 'Calzedonia',
    price: 19.90,
    images: ['/media/RID2576937J-FI.jpg'],
    category: 'intimo',
    subcategory: 'brasiliana',
    colors: 5,
    sizes: ['S', 'M', 'L'],
    description: 'Slip brasiliana in pizzo. Taglio che valorizza il corpo.',
    descriptionEn: 'Brazilian lace panty. Cut that enhances the body.',
    inStock: true,
  },
  // Slip - Perizoma / Tanga
  {
    id: 'perizoma-001',
    name: 'Perizoma Pizzo Elegante',
    nameEn: 'Elegant Lace Thong',
    brand: 'Intimissimi',
    price: 15.90,
    images: ['/media/RID2581942J-FI.jpg'],
    category: 'intimo',
    subcategory: 'perizoma',
    colors: 6,
    sizes: ['S', 'M', 'L'],
    description: 'Perizoma in pizzo elegante. Perfetto per evitare le righe.',
    descriptionEn: 'Elegant lace thong. Perfect to avoid visible lines.',
    inStock: true,
  },
  // Slip - Invisibile
  {
    id: 'invisibile-001',
    name: 'Slip Invisibile Tinta Unita',
    nameEn: 'Invisible Solid Panty',
    brand: 'Tezenis',
    price: 14.90,
    images: ['/media/RSD2577938J-FI.jpg'],
    category: 'intimo',
    subcategory: 'invisibile',
    colors: 4,
    sizes: ['S', 'M', 'L'],
    description: 'Slip invisibile in cotone. Perfetto sotto ogni abito.',
    descriptionEn: 'Invisible cotton panty. Perfect under any dress.',
    inStock: true,
    material: ['Cotone'],
  },
  // Pigiami - Lunghi
  {
    id: 'pigiama-lungo-001',
    name: 'Pigiama Lungo Satinato',
    nameEn: 'Long Satin Pajamas',
    brand: 'Tezenis',
    price: 59.90,
    images: ['/media/PCD700M949J-FI.jpg'],
    category: 'pigiami',
    subcategory: 'pigiami-lunghi',
    colors: 4,
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Pigiama lungo in satin. Massimo comfort per la notte.',
    descriptionEn: 'Long satin pajamas. Maximum comfort for the night.',
    inStock: true,
  },
  {
    id: 'pigiama-lungo-002',
    name: 'Pigiama Lungo Cotone',
    nameEn: 'Long Cotton Pajamas',
    brand: 'Intimissimi',
    price: 49.90,
    images: ['/media/PCD700M949J-F.jpg'],
    category: 'pigiami',
    subcategory: 'pigiami-lunghi',
    colors: 5,
    sizes: ['S', 'M', 'L'],
    description: 'Pigiama lungo in cotone. Perfetto per ogni stagione.',
    descriptionEn: 'Long cotton pajamas. Perfect for every season.',
    inStock: true,
    material: ['Cotone'],
  },
  // Pigiami - Corti
  {
    id: 'pigiama-corto-001',
    name: 'Pigiama Corto Estate',
    nameEn: 'Short Summer Pajamas',
    brand: 'Tezenis',
    price: 39.90,
    images: ['/media/PCN12S1467-FI.jpg'],
    category: 'pigiami',
    subcategory: 'pigiami-corti',
    colors: 6,
    sizes: ['S', 'M', 'L'],
    description: 'Pigiama corto perfetto per l\'estate. Fresco e comodo.',
    descriptionEn: 'Short pajamas perfect for summer. Fresh and comfortable.',
    inStock: true,
  },
  // Leggings
  {
    id: 'leggings-001',
    name: 'Leggings Alte Fitness',
    nameEn: 'High Waist Fitness Leggings',
    brand: 'Calzedonia',
    price: 29.90,
    images: ['/media/RBD2576937J-FI.jpg'],
    category: 'casual',
    subcategory: 'leggings',
    colors: 5,
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Leggings alte in tessuto tecnico. Perfette per sport e casual.',
    descriptionEn: 'High waist technical fabric leggings. Perfect for sport and casual.',
    inStock: true,
  },
  {
    id: 'leggings-002',
    name: 'Leggings Elasticizzate',
    nameEn: 'Elasticated Leggings',
    brand: 'Tezenis',
    price: 24.90,
    images: ['/media/RBD2578019-FI.jpg'],
    category: 'casual',
    subcategory: 'leggings',
    colors: 4,
    sizes: ['S', 'M', 'L'],
    description: 'Leggings elasticizzate comode. Per tutti i giorni.',
    descriptionEn: 'Comfortable elasticated leggings. For everyday.',
    inStock: true,
  },
  // Pantaloni
  {
    id: 'pantaloni-001',
    name: 'Pantaloni Larghi Comfort',
    nameEn: 'Comfort Wide Leg Pants',
    brand: 'Intimissimi',
    price: 45.90,
    images: ['/media/RBD2576937J-FI.jpg'],
    category: 'casual',
    subcategory: 'pantaloni',
    colors: 3,
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Pantaloni larghi in tessuto morbido. Massimo comfort.',
    descriptionEn: 'Wide leg pants in soft fabric. Maximum comfort.',
    inStock: true,
  },
  // Maglie - Dolcevita
  {
    id: 'dolcevita-001',
    name: 'Dolcevita Cotone',
    nameEn: 'Cotton Turtleneck',
    brand: 'Calzedonia',
    price: 34.90,
    images: ['/media/RBD2578019-FI.jpg'],
    category: 'casual',
    subcategory: 'dolcevita',
    colors: 6,
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Dolcevita in cotone morbido. Perfetto per l\'inverno.',
    descriptionEn: 'Soft cotton turtleneck. Perfect for winter.',
    inStock: true,
    material: ['Cotone'],
  },
  // Maglie - Maniche lunghe
  {
    id: 'maniche-lunghe-001',
    name: 'Maglia Maniche Lunghe',
    nameEn: 'Long Sleeve Top',
    brand: 'Tezenis',
    price: 29.90,
    images: ['/media/RBD2576937J-FI.jpg'],
    category: 'casual',
    subcategory: 'maniche-lunghe',
    colors: 5,
    sizes: ['S', 'M', 'L'],
    description: 'Maglia a maniche lunghe in cotone. Comoda e versatile.',
    descriptionEn: 'Long sleeve cotton top. Comfortable and versatile.',
    inStock: true,
    material: ['Cotone'],
  },
  // Maglie - Maniche corte
  {
    id: 'maniche-corte-001',
    name: 'Maglia Maniche Corte',
    nameEn: 'Short Sleeve Top',
    brand: 'Intimissimi',
    price: 24.90,
    images: ['/media/RBD2578019-FI.jpg'],
    category: 'casual',
    subcategory: 'maniche-corte',
    colors: 7,
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Maglia a maniche corte. Fresca e comoda.',
    descriptionEn: 'Short sleeve top. Fresh and comfortable.',
    inStock: true,
  },
  // Maglie - Top e canotte
  {
    id: 'top-001',
    name: 'Top Elegante Pizzo',
    nameEn: 'Elegant Lace Top',
    brand: 'Calzedonia',
    price: 32.90,
    images: ['/media/RBD2576937J-FI.jpg'],
    category: 'casual',
    subcategory: 'top',
    colors: 4,
    sizes: ['S', 'M', 'L'],
    description: 'Top elegante in pizzo. Perfetto per l\'estate.',
    descriptionEn: 'Elegant lace top. Perfect for summer.',
    inStock: true,
  },
  // Body
  {
    id: 'body-001',
    name: 'Body Pizzo Elegante',
    nameEn: 'Elegant Lace Bodysuit',
    brand: 'Intimissimi',
    price: 42.90,
    images: ['/media/BOD2577938J-FI.jpg'],
    category: 'intimo',
    subcategory: 'body',
    colors: 5,
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'Body in pizzo elegante. Perfetto per ogni occasione.',
    descriptionEn: 'Elegant lace bodysuit. Perfect for every occasion.',
    badge: 'NEW',
    inStock: true,
  },
  // Collant - Coprenti
  {
    id: 'collant-coprenti-001',
    name: 'Collant Coprenti 40 Denari',
    nameEn: '40 Denier Opaque Tights',
    brand: 'Golden Lady',
    price: 8.90,
    images: ['/media/gcd0383ncn002_collant_effetto_pizzo_01.jpg'],
    category: 'calze',
    subcategory: 'collant-coprenti',
    colors: 4,
    sizes: ['Unica'],
    description: 'Collant coprenti 40 denari. Perfette per l\'inverno.',
    descriptionEn: '40 denier opaque tights. Perfect for winter.',
    inStock: true,
  },
  // Collant - Velati
  {
    id: 'collant-velati-001',
    name: 'Collant Velati 15 Denari',
    nameEn: '15 Denier Sheer Tights',
    brand: 'Golden Lady',
    price: 7.90,
    images: ['/media/gcd0376ncn002_collant_in_tulle_con_applicazione_strass_01.jpg'],
    category: 'calze',
    subcategory: 'collant-velati',
    colors: 5,
    sizes: ['Unica'],
    description: 'Collant velati 15 denari. Eleganti e raffinati.',
    descriptionEn: '15 denier sheer tights. Elegant and refined.',
    inStock: true,
  },
  // Collant - Rete
  {
    id: 'collant-rete-001',
    name: 'Collant Rete Fantasia',
    nameEn: 'Mesh Pattern Tights',
    brand: 'Golden Lady',
    price: 11.90,
    images: ['/media/gcd0376ncn002_collant_in_tulle_con_applicazione_strass_01.jpg'],
    category: 'calze',
    subcategory: 'collant-rete',
    colors: 3,
    sizes: ['Unica'],
    description: 'Collant rete con fantasia. Per un look originale.',
    descriptionEn: 'Mesh tights with pattern. For an original look.',
    inStock: true,
  },
  // Collant - Fantasia
  {
    id: 'collant-fantasia-001',
    name: 'Collant Fantasia Pizzo',
    nameEn: 'Lace Pattern Tights',
    brand: 'Golden Lady',
    price: 12.90,
    images: ['/media/gcd0383ncn002_collant_effetto_pizzo_01.jpg'],
    category: 'calze',
    subcategory: 'collant-fantasia',
    colors: 4,
    sizes: ['Unica'],
    description: 'Collant con fantasia pizzo. Eleganti e sofisticate.',
    descriptionEn: 'Lace pattern tights. Elegant and sophisticated.',
    inStock: true,
  },
  // Collant - Autoreggenti
  {
    id: 'autoreggenti-001',
    name: 'Collant Autoreggenti',
    nameEn: 'Stay-up Tights',
    brand: 'Golden Lady',
    price: 13.90,
    images: ['/media/gcd0376ncn002_collant_in_tulle_con_applicazione_strass_01.jpg'],
    category: 'calze',
    subcategory: 'autoreggenti',
    colors: 5,
    sizes: ['Unica'],
    description: 'Collant autoreggenti. Comode e pratiche.',
    descriptionEn: 'Stay-up tights. Comfortable and practical.',
    inStock: true,
  },
  // Calze - Mini calzini
  {
    id: 'mini-calzini-001',
    name: 'Mini Calzini Cotone',
    nameEn: 'Cotton Mini Socks',
    brand: 'Calzedonia',
    price: 4.90,
    images: ['/media/gcd0383ncn002_collant_effetto_pizzo_01.jpg'],
    category: 'calze',
    subcategory: 'mini-calzini',
    colors: 8,
    sizes: ['Unica'],
    description: 'Mini calzini in cotone. Perfetti per sneakers.',
    descriptionEn: 'Cotton mini socks. Perfect for sneakers.',
    inStock: true,
  },
  // Calze - Corte
  {
    id: 'calze-corte-001',
    name: 'Calze Corte Cotone',
    nameEn: 'Cotton Short Socks',
    brand: 'Tezenis',
    price: 5.90,
    images: ['/media/gcd0376ncn002_collant_in_tulle_con_applicazione_strass_01.jpg'],
    category: 'calze',
    subcategory: 'calze-corte',
    colors: 6,
    sizes: ['Unica'],
    description: 'Calze corte in cotone. Comode e traspiranti.',
    descriptionEn: 'Short cotton socks. Comfortable and breathable.',
    inStock: true,
  },
  // Calze - Lunghe
  {
    id: 'calze-lunghe-001',
    name: 'Calze Lunghe Cotone',
    nameEn: 'Cotton Long Socks',
    brand: 'Intimissimi',
    price: 7.90,
    images: ['/media/gcd0383ncn002_collant_effetto_pizzo_01.jpg'],
    category: 'calze',
    subcategory: 'calze-lunghe',
    colors: 5,
    sizes: ['Unica'],
    description: 'Calze lunghe in cotone. Perfette per l\'inverno.',
    descriptionEn: 'Long cotton socks. Perfect for winter.',
    inStock: true,
  },
  // Calze - Fantasmini
  {
    id: 'fantasmini-001',
    name: 'Fantasmini Cotone',
    nameEn: 'Cotton Ankle Socks',
    brand: 'Calzedonia',
    price: 4.90,
    images: ['/media/gcd0376ncn002_collant_in_tulle_con_applicazione_strass_01.jpg'],
    category: 'calze',
    subcategory: 'fantasmini',
    colors: 7,
    sizes: ['Unica'],
    description: 'Fantasmini in cotone. Invisibili e comodi.',
    descriptionEn: 'Cotton ankle socks. Invisible and comfortable.',
    inStock: true,
  },
  // Calze - Velate / GAMBALETTO
  {
    id: 'calze-velate-001',
    name: 'Calze Velate Gambaletto',
    nameEn: 'Sheer Over-the-Knee Socks',
    brand: 'Golden Lady',
    price: 9.90,
    images: ['/media/gcd0383ncn002_collant_effetto_pizzo_01.jpg'],
    category: 'calze',
    subcategory: 'calze-velate',
    colors: 4,
    sizes: ['Unica'],
    description: 'Calze velate gambaletto. Eleganti e raffinate.',
    descriptionEn: 'Sheer over-the-knee socks. Elegant and refined.',
    inStock: true,
  },
  // Pack Products - 3-item packs
  {
    id: 'pack-slip-3',
    name: 'Pack di 3 Slip Pizzo',
    nameEn: 'Pack of 3 Lace Panties',
    brand: 'Intimissimi',
    price: 44.90,
    originalPrice: 59.70,
    images: ['/media/RID2576937J-FI.jpg', '/media/RID2581942J-FI.jpg', '/media/RSD2577938J-FI.jpg'],
    category: 'intimo',
    subcategory: 'slip',
    colors: 3,
    sizes: ['S', 'M', 'L'],
    description: 'Pack di 3 slip in pizzo elegante. Include 3 colori diversi in un unico set conveniente.',
    descriptionEn: 'Pack of 3 elegant lace panties. Includes 3 different colors in one convenient set.',
    badge: 'SALE',
    inStock: true,
    isPack: true,
    packQuantity: 3,
    packColors: ['#DC143C', '#000000', '#FFFFFF'],
  },
  {
    id: 'pack-reggiseno-3',
    name: 'Pack di 3 Reggiseni Pizzo',
    nameEn: 'Pack of 3 Lace Bras',
    brand: 'Calzedonia',
    price: 89.90,
    originalPrice: 119.70,
    images: ['/media/RBD2576937J-FI.jpg', '/media/RBD2578019-FI.jpg', '/media/RSD2577938J-FI.jpg'],
    category: 'intimo',
    subcategory: 'reggiseni',
    colors: 3,
    sizes: ['II', 'III', 'IV'],
    description: 'Pack di 3 reggiseni in pizzo. Include 3 colori classici per ogni occasione.',
    descriptionEn: 'Pack of 3 lace bras. Includes 3 classic colors for every occasion.',
    badge: 'NEW',
    inStock: true,
    isPack: true,
    packQuantity: 3,
    packColors: ['#DC143C', '#000000', '#8B0000'],
  },
  {
    id: 'pack-intimo-3',
    name: 'Pack di 3 Set Intimo Completo',
    nameEn: 'Pack of 3 Complete Lingerie Sets',
    brand: 'Tezenis',
    price: 129.90,
    originalPrice: 179.70,
    images: ['/media/RSD2577938J-FI.jpg', '/media/RBD2576937J-FI.jpg', '/media/SBD2577938J-FI.jpg'],
    category: 'intimo',
    subcategory: 'reggiseni',
    colors: 3,
    sizes: ['S', 'M', 'L'],
    description: 'Pack di 3 set intimo completi (reggiseno + slip). Include 3 combinazioni di colori eleganti.',
    descriptionEn: 'Pack of 3 complete lingerie sets (bra + panty). Includes 3 elegant color combinations.',
    badge: 'SALE',
    inStock: true,
    isPack: true,
    packQuantity: 3,
    packColors: ['#FF69B4', '#DC143C', '#8B0000'],
  },
];

export function getProductsByCategory(category: string): Product[] {
  return products.filter(p => p.category === category);
}

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id);
}

export function getProductsBySubcategory(category: string, subcategory: string): Product[] {
  return products.filter(p => p.category === category && p.subcategory === subcategory);
}

export function getRelatedProducts(productId: string, brand: string, limit: number = 6): Product[] {
  return products
    .filter(p => p.id !== productId && p.brand === brand)
    .slice(0, limit);
}

export function getProductsByBrand(brand: string): Product[] {
  return products.filter(p => p.brand === brand);
}

export function getSeasonalProducts(limit: number = 8): Product[] {
  // Get products with NEW badge (seasonal/new arrivals)
  const seasonal = products
    .filter(p => p.badge === 'NEW')
    .slice(0, limit);
  
  // If not enough NEW products, add SALE products
  if (seasonal.length < limit) {
    const saleProducts = products
      .filter(p => p.badge === 'SALE' && !seasonal.find(sp => sp.id === p.id))
      .slice(0, limit - seasonal.length);
    return [...seasonal, ...saleProducts];
  }
  
  return seasonal;
}

export function getMostLikedProducts(limit: number = 8): Product[] {
  // Get products with badges (NEW or SALE) as "most liked"
  // In a real app, this would be based on actual user interactions/ratings
  const mostLiked = products
    .filter(p => p.badge === 'NEW' || p.badge === 'SALE')
    .sort((a, b) => {
      // Prioritize NEW over SALE
      if (a.badge === 'NEW' && b.badge !== 'NEW') return -1;
      if (a.badge !== 'NEW' && b.badge === 'NEW') return 1;
      return 0;
    })
    .slice(0, limit);
  
  return mostLiked;
}
